export const CAR_LIST_REQUEST = "CAR_LIST_REQUEST";
export const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
export const CAR_LIST_FAIL = "CAR_LIST_FAIL";

export const CAR_ADD_REQUEST = "CAR_ADD_REQUEST";
export const CAR_ADD_SUCCESS = "CAR_ADD_SUCCESS";
export const CAR_ADD_FAIL = "CAR_ADD_FAIL";

export const CAR_SEARCH_REQUEST = "CAR_SEARCH_REQUEST";
export const CAR_SEARCH_SUCCESS = "CAR_SEARCH_SUCCESS";
export const CAR_SEARCH_FAIL = "CAR_SEARCH_FAIL";

export const CAR_SINGLE_REQUEST = "CAR_SINGLE_REQUEST";
export const CAR_SINGLE_SUCCESS = "CAR_SINGLE_SUCCESS";
export const CAR_SINGLE_FAIL = "CAR_SINGLE_FAIL";

export const CAR_DELETE_REQUEST = "CAR_DELETE_REQUEST";
export const CAR_DELETE_SUCCESS = "CAR_DELETE_SUCCESS";
export const CAR_DELETE_FAIL = "CAR_DELETE_FAIL";
