export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const SET_LOCALSTORAGE_DATA = "SET_LOCALSTORAGE_DATA";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_BOOKCAR_REQUEST = "GET_BOOKCAR_REQUEST";
export const GET_BOOKCAR_SUCCESS = "GET_BOOKCAR_SUCCESS";
export const GET_BOOKCAR_FAIL = "GET_BOOKCAR_FAIL";
